version: '3.8'

services:
  postgres-master:
    image: postgres:14
    container_name: repl-master
    environment:
      POSTGRES_DB: medical_records
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    command: |
      postgres
      -c wal_level=replica
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
    ports:
      - "5432:5432"
    volumes:
      - ./init-master.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-slave1:
    image: postgres:14
    container_name: repl-slave1
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    depends_on:
      - postgres-master
    entrypoint: >
      bash -c '
      sleep 20;
      rm -rf /var/lib/postgresql/data/*;
      PGPASSWORD=postgres pg_basebackup -h postgres-master -U postgres -D /var/lib/postgresql/data -P -v -R -W;
      chown -R postgres:postgres /var/lib/postgresql/data;
      postgres
      '
      
  postgres-slave2:
    image: postgres:14
    container_name: repl-slave2  
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    depends_on:
      - postgres-master
    entrypoint: >
      bash -c '
      sleep 25;
      rm -rf /var/lib/postgresql/data/*;
      PGPASSWORD=postgres pg_basebackup -h postgres-master -U postgres -D /var/lib/postgresql/data -P -v -R -W;
      chown -R postgres:postgres /var/lib/postgresql/data;
      postgres
      '
